apiVersion: v1
kind: Service
metadata:
  labels:
    app: tomcat-helm
  name: tomcat-helm
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tomcat-helm
  type: NodePort
