apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tomcat-helm
  name: tomcat-helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tomcat-helm
  template:
    metadata:
      labels:
        app: tomcat-helm
    spec:
      containers:
      - image: fabric8/tomcat-9:latest
        name: tomcat-9
       
